version: '2.1'

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: junit.xml
